### ISSUE TITLE
Not compatible with acquia/blt-behat

### ISSUE THREAD

**Issue by greggmarshall** [lcatlett/blt-ddev#6]
In BLT 12, now that the Behat support has been moved into the acquia/blt-behat plug-in, when doing

`blt recipes:ddev --no-interaction`

results in the error 

`PHP Fatal error:  Uncaught Error: Class 'Acquia\Blt\Robo\Commands\Tests\BehatCommand' not found in /home/gregg/drupalsites/brc-local/vendor/lcatlett/blt-ddev/src/Blt/Plugin/Commands/BehatDdevCommand.php:7`

It appears the BehatCommand has moved from `vendor/acquia/blt/src/Robo/Commands/Tests/BehatCommand.php` to `vendor/acquia/blt-behat/src/Blt/Plugin/Commands/BehatTestCommand.php`

**Comment by travelertt** [comment]
Also having this problem.

`PHP Fatal error:  Uncaught Error: Class "Acquia\Blt\Robo\Commands\Tests\BehatCommand" not found in /Users/torytrone/Sites/ucgc8/vendor/lcatlett/blt-ddev/src/Blt/Plugin/Commands/BehatDdevCommand.php:7
Stack trace:
#0 /Users/torytrone/Sites/ucgc8/vendor/composer/ClassLoader.php(444): include()
#1 /Users/torytrone/Sites/ucgc8/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Users/torytron...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Lcatlett\\BltDde...')
#3 /Users/torytrone/Sites/ucgc8/vendor/consolidation/robo/src/Runner.php(370): class_exists('Lcatlett\\BltDde...')
#4 /Users/torytrone/Sites/ucgc8/vendor/consolidation/robo/src/Runner.php(342): Robo\Runner->instantiateCommandClass('Lcatlett\\BltDde...')
#5 /Users/torytrone/Sites/ucgc8/vendor/consolidation/robo/src/Runner.php(315): Robo\Runner->registerCommandClass(Object(Acquia\Blt\Robo\Application), 'Lcatlett\\BltDde...')
#6 /Users/torytrone/Sites/ucgc8/vendor/consolidation/robo/src/Runner.php(276): Robo\Runner->registerCommandClasses(Object(Acquia\Blt\Robo\Application), Array)
#7 /Users/torytrone/Sites/ucgc8/vendor/acquia/blt/src/Robo/Blt.php(252): Robo\Runner->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Acquia\Blt\Robo\Application), Array)
#8 /Users/torytrone/Sites/ucgc8/vendor/acquia/blt/bin/blt-robo-run.php(35): Acquia\Blt\Robo\Blt->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /Users/torytrone/Sites/ucgc8/vendor/acquia/blt/bin/blt-robo.php(15): require_once('/Users/torytron...')
#10 /Users/torytrone/Sites/ucgc8/vendor/acquia/blt/bin/blt(11): require_once('/Users/torytron...')
#11 {main}
  thrown in /Users/torytrone/Sites/ucgc8/vendor/lcatlett/blt-ddev/src/Blt/Plugin/Commands/BehatDdevCommand.php on line 7

Fatal error: Uncaught Error: Class "Acquia\Blt\Robo\Commands\Tests\BehatCommand" not found in /Users/torytrone/Sites/ucgc8/vendor/lcatlett/blt-ddev/src/Blt/Plugin/Commands/BehatDdevCommand.php:7
Stack trace:
#0 /Users/torytrone/Sites/ucgc8/vendor/composer/ClassLoader.php(444): include()
#1 /Users/torytrone/Sites/ucgc8/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Users/torytron...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Lcatlett\\BltDde...')
#3 /Users/torytrone/Sites/ucgc8/vendor/consolidation/robo/src/Runner.php(370): class_exists('Lcatlett\\BltDde...')
#4 /Users/torytrone/Sites/ucgc8/vendor/consolidation/robo/src/Runner.php(342): Robo\Runner->instantiateCommandClass('Lcatlett\\BltDde...')
#5 /Users/torytrone/Sites/ucgc8/vendor/consolidation/robo/src/Runner.php(315): Robo\Runner->registerCommandClass(Object(Acquia\Blt\Robo\Application), 'Lcatlett\\BltDde...')
#6 /Users/torytrone/Sites/ucgc8/vendor/consolidation/robo/src/Runner.php(276): Robo\Runner->registerCommandClasses(Object(Acquia\Blt\Robo\Application), Array)
#7 /Users/torytrone/Sites/ucgc8/vendor/acquia/blt/src/Robo/Blt.php(252): Robo\Runner->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Acquia\Blt\Robo\Application), Array)
#8 /Users/torytrone/Sites/ucgc8/vendor/acquia/blt/bin/blt-robo-run.php(35): Acquia\Blt\Robo\Blt->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /Users/torytrone/Sites/ucgc8/vendor/acquia/blt/bin/blt-robo.php(15): require_once('/Users/torytron...')
#10 /Users/torytrone/Sites/ucgc8/vendor/acquia/blt/bin/blt(11): require_once('/Users/torytron...')
#11 {main}
  thrown in /Users/torytrone/Sites/ucgc8/vendor/lcatlett/blt-ddev/src/Blt/Plugin/Commands/BehatDdevCommand.php on line 7`
